# Generated by Django 5.2.7 on 2025-10-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orederitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederItem',
            new_name='OrderItem',
        ),
    ]
