# Generated by Django 5.2.7 on 2025-10-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_orederitem_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
