# Generated by Django 5.2.7 on 2025-10-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_merchant_id_order_payment_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
